version: '3'

services:
  cells:
    image: cells
    build: .
    container_name: cells
    hostname: cells
    tty: true
    ports:
      - 2015:2015
    links:
      - db
    volumes:
      - cellsdata:/home/cells/.config/pydio/cells

  database:
    image: mariadb:latest
    hostname: database
    container_name: database
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true

volumes:
  cellsdata:
